name: Docs

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Set environment for version
        run: long="${{ github.ref }}"; version=${long#"refs/tags/v"}; echo "version=${version}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - uses: actions/configure-pages@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Generate Docs
        run: ./gradlew dokkaHtml
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build/dokka/html
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
